import { Category, Article, Service, Client, OrderWithDetails, Settings } from '@/types/database';

export const initialSettings: Settings = {
  id: 'set-001',
  shop_name: 'Pressing Royal Ivoire',
  phone: '+225 07 48 92 11 00',
  address: 'Deux-Plateaux Vallons, Rue des Jardins, Abidjan',
  currency: 'FCFA',
  default_pickup_days: 2,
  express_surcharge_percent: 50,
  sms_api_key: null,
  whatsapp_api_url: null,
  whatsapp_template: 'Bonjour {{client_name}} ✨ Votre linge (Commande #{{order_number}}) est PRÊT au {{shop_name}}. Reste à régler : {{remaining_amount}} {{currency}}. Merci pour votre confiance !',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Hauts & Chemises', icon: 'Shirt', display_order: 1, created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Bas & Pantalons', icon: 'Scissors', display_order: 2, created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Costumes & Robes', icon: 'Sparkles', display_order: 3, created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Traditionnel & Cérémonie', icon: 'Crown', display_order: 4, created_at: new Date().toISOString() },
  { id: 'cat-5', name: 'Linge de Maison', icon: 'BedDouble', display_order: 5, created_at: new Date().toISOString() },
  { id: 'cat-6', name: 'Chaussures & Maroquinerie', icon: 'Footprints', display_order: 6, created_at: new Date().toISOString() },
];

export const initialServices: Service[] = [
  { id: 'srv-1', code: 'wash', name: 'Lavage Seul', price_multiplier: 0.7, additional_fee: 0, default_delay_days: 1, created_at: new Date().toISOString() },
  { id: 'srv-2', code: 'iron', name: 'Repassage Seul', price_multiplier: 0.6, additional_fee: 0, default_delay_days: 1, created_at: new Date().toISOString() },
  { id: 'srv-3', code: 'full', name: 'Lavage + Repassage (Complet)', price_multiplier: 1.0, additional_fee: 0, default_delay_days: 2, created_at: new Date().toISOString() },
  { id: 'srv-4', code: 'express', name: 'Option Express (J+0 ou 24h)', price_multiplier: 1.5, additional_fee: 500, default_delay_days: 0, created_at: new Date().toISOString() },
];

export const initialArticles: Article[] = [
  { id: 'art-1', category_id: 'cat-1', name: 'Chemise Homme / Femme', base_price: 1000, icon: 'Shirt', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-2', category_id: 'cat-1', name: 'Polo / T-Shirt', base_price: 800, icon: 'Shirt', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-3', category_id: 'cat-1', name: 'Veste / Blazer', base_price: 2000, icon: 'Sparkles', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-4', category_id: 'cat-2', name: 'Pantalon Costume / Ville', base_price: 1200, icon: 'Scissors', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-5', category_id: 'cat-2', name: 'Jean / Pantalon Casual', base_price: 1000, icon: 'Scissors', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-6', category_id: 'cat-2', name: 'Jupe Plissée / Droite', base_price: 1200, icon: 'Scissors', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-7', category_id: 'cat-3', name: 'Costume 2 Pièces', base_price: 3000, icon: 'Sparkles', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-8', category_id: 'cat-3', name: 'Costume 3 Pièces Prestige', base_price: 4500, icon: 'Sparkles', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-9', category_id: 'cat-3', name: 'Robe de Soirée / Cocktail', base_price: 3500, icon: 'Sparkles', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-10', category_id: 'cat-4', name: 'Boubou Bazin Riche 3P', base_price: 5000, icon: 'Crown', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-11', category_id: 'cat-4', name: 'Complet Pagne Traditionnel', base_price: 2500, icon: 'Crown', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-12', category_id: 'cat-5', name: 'Couette Lit 2 Places', base_price: 4000, icon: 'BedDouble', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-13', category_id: 'cat-5', name: 'Drap & Housse (Paire)', base_price: 2000, icon: 'BedDouble', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-14', category_id: 'cat-5', name: 'Rideaux (La Paire)', base_price: 3500, icon: 'BedDouble', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-15', category_id: 'cat-6', name: 'Baskets / Sneakers Premium', base_price: 2500, icon: 'Footprints', is_active: true, created_at: new Date().toISOString() },
  { id: 'art-16', category_id: 'cat-6', name: 'Veste Cuir & Daim', base_price: 6000, icon: 'Footprints', is_active: true, created_at: new Date().toISOString() },
];

export const initialClients: Client[] = [
  {
    id: 'cli-1',
    name: 'Kouassi Jean-Philippe',
    phone: '+225 07 47 12 34 56',
    address: 'Cocody Angré 7ème Tranche',
    notes: 'Client VIP - repassage amidonné sur chemises',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-2',
    name: 'Amina Diallo Koné',
    phone: '+225 05 85 99 22 11',
    address: 'Plateau Indénié',
    notes: 'Attention Bazin fragile, pliage sous film',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-3',
    name: 'Marc-Aurèle Brou',
    phone: '+225 01 02 03 04 05',
    address: 'Riviera Bonoumin',
    notes: 'Paiement Wave habituel',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cli-4',
    name: 'Fatou Bamba',
    phone: '+225 07 11 22 33 44',
    address: 'Marcory Zone 4',
    notes: 'Livraison samedi matin souhaitée',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const now = new Date();
const formatIso = (offsetDays: number) => {
  const d = new Date(now.getTime() + offsetDays * 86400000);
  return d.toISOString();
};

export const initialOrders: OrderWithDetails[] = [
  {
    id: 'ord-101',
    order_number: 'PRS-2026-0038',
    client_id: 'cli-1',
    client: initialClients[0],
    status: 'to_process',
    total_amount: 5000,
    advance_amount: 2000,
    remaining_amount: 3000,
    payment_status: 'partially_paid',
    payment_method: 'wave',
    pickup_date: formatIso(1),
    is_express: false,
    notes: 'Chemises col empesé léger',
    qr_code: 'PRS-2026-0038|CLI-1|5000',
    notification_sent: false,
    notification_sent_at: null,
    created_at: formatIso(-1),
    updated_at: formatIso(-1),
    items: [
      {
        id: 'item-101-1',
        order_id: 'ord-101',
        article_id: 'art-1',
        article_name: 'Chemise Homme / Femme',
        service_code: 'full',
        quantity: 3,
        unit_price: 1000,
        total_price: 3000,
        notes: 'Col blanc',
        created_at: formatIso(-1),
      },
      {
        id: 'item-101-2',
        order_id: 'ord-101',
        article_id: 'art-3',
        article_name: 'Veste / Blazer',
        service_code: 'full',
        quantity: 1,
        unit_price: 2000,
        total_price: 2000,
        notes: 'Bleu marine',
        created_at: formatIso(-1),
      },
    ],
    payments: [
      {
        id: 'pay-1',
        order_id: 'ord-101',
        amount: 2000,
        payment_method: 'wave',
        amount_received: 2000,
        change_returned: 0,
        reference: 'WAVE-TX-9982',
        cashier_note: 'Acompte réception Wave',
        created_at: formatIso(-1),
      },
    ],
  },
  {
    id: 'ord-102',
    order_number: 'PRS-2026-0039',
    client_id: 'cli-2',
    client: initialClients[1],
    status: 'in_progress',
    total_amount: 8500,
    advance_amount: 8500,
    remaining_amount: 0,
    payment_status: 'paid',
    payment_method: 'orange_money',
    pickup_date: formatIso(1),
    is_express: true,
    notes: 'Express 24h - Bazin brodé',
    qr_code: 'PRS-2026-0039|CLI-2|8500',
    notification_sent: false,
    notification_sent_at: null,
    created_at: formatIso(-0.5),
    updated_at: formatIso(-0.2),
    items: [
      {
        id: 'item-102-1',
        order_id: 'ord-102',
        article_id: 'art-10',
        article_name: 'Boubou Bazin Riche 3P',
        service_code: 'full',
        quantity: 1,
        unit_price: 5000,
        total_price: 5000,
        notes: 'Teinture violette délicate',
        created_at: formatIso(-0.5),
      },
      {
        id: 'item-102-2',
        order_id: 'ord-102',
        article_id: 'art-9',
        article_name: 'Robe de Soirée / Cocktail',
        service_code: 'full',
        quantity: 1,
        unit_price: 3500,
        total_price: 3500,
        notes: 'Perles sur buste',
        created_at: formatIso(-0.5),
      },
    ],
    payments: [
      {
        id: 'pay-2',
        order_id: 'ord-102',
        amount: 8500,
        payment_method: 'orange_money',
        amount_received: 8500,
        change_returned: 0,
        reference: 'OM-CI-4821',
        cashier_note: 'Payé d’avance en intégralité',
        created_at: formatIso(-0.5),
      },
    ],
  },
  {
    id: 'ord-103',
    order_number: 'PRS-2026-0040',
    client_id: 'cli-3',
    client: initialClients[2],
    status: 'ready',
    total_amount: 4200,
    advance_amount: 2000,
    remaining_amount: 2200,
    payment_status: 'partially_paid',
    payment_method: 'cash',
    pickup_date: formatIso(0),
    is_express: false,
    notes: 'Costume sur cintre avec housse de protection',
    qr_code: 'PRS-2026-0040|CLI-3|4200',
    notification_sent: true,
    notification_sent_at: formatIso(-0.1),
    created_at: formatIso(-2),
    updated_at: formatIso(-0.1),
    items: [
      {
        id: 'item-103-1',
        order_id: 'ord-103',
        article_id: 'art-7',
        article_name: 'Costume 2 Pièces',
        service_code: 'full',
        quantity: 1,
        unit_price: 3000,
        total_price: 3000,
        notes: 'Gris anthracite',
        created_at: formatIso(-2),
      },
      {
        id: 'item-103-2',
        order_id: 'ord-103',
        article_id: 'art-4',
        article_name: 'Pantalon Costume / Ville',
        service_code: 'iron',
        quantity: 1,
        unit_price: 1200,
        total_price: 1200,
        notes: 'Pli marqué',
        created_at: formatIso(-2),
      },
    ],
    payments: [
      {
        id: 'pay-3',
        order_id: 'ord-103',
        amount: 2000,
        payment_method: 'cash',
        amount_received: 2000,
        change_returned: 0,
        reference: 'CASH-DEP-040',
        cashier_note: 'Acompte espèces',
        created_at: formatIso(-2),
      },
    ],
  },
  {
    id: 'ord-104',
    order_number: 'PRS-2026-0041',
    client_id: 'cli-4',
    client: initialClients[3],
    status: 'delivered',
    total_amount: 6000,
    advance_amount: 6000,
    remaining_amount: 0,
    payment_status: 'paid',
    payment_method: 'wave',
    pickup_date: formatIso(-1),
    is_express: false,
    notes: 'Linge de lit récupéré hier soir',
    qr_code: 'PRS-2026-0041|CLI-4|6000',
    notification_sent: true,
    notification_sent_at: formatIso(-1.2),
    created_at: formatIso(-3),
    updated_at: formatIso(-1),
    items: [
      {
        id: 'item-104-1',
        order_id: 'ord-104',
        article_id: 'art-12',
        article_name: 'Couette Lit 2 Places',
        service_code: 'full',
        quantity: 1,
        unit_price: 4000,
        total_price: 4000,
        notes: '',
        created_at: formatIso(-3),
      },
      {
        id: 'item-104-2',
        order_id: 'ord-104',
        article_id: 'art-13',
        article_name: 'Drap & Housse (Paire)',
        service_code: 'full',
        quantity: 1,
        unit_price: 2000,
        total_price: 2000,
        notes: '',
        created_at: formatIso(-3),
      },
    ],
    payments: [
      {
        id: 'pay-4',
        order_id: 'ord-104',
        amount: 6000,
        payment_method: 'wave',
        amount_received: 6000,
        change_returned: 0,
        reference: 'WAVE-FULL-41',
        cashier_note: 'Payé et remis au client',
        created_at: formatIso(-1),
      },
    ],
  },
];
